2024-07-23 18:23:56,008 INFO    MainThread:21832 [wandb_setup.py:_flush():76] Current SDK version is 0.17.4
2024-07-23 18:23:56,010 INFO    MainThread:21832 [wandb_setup.py:_flush():76] Configure stats pid to 21832
2024-07-23 18:23:56,010 INFO    MainThread:21832 [wandb_setup.py:_flush():76] Loading settings from C:\Users\PC\.config\wandb\settings
2024-07-23 18:23:56,010 INFO    MainThread:21832 [wandb_setup.py:_flush():76] Loading settings from c:\Users\PC\Documents\MLCodes\wandb\settings
2024-07-23 18:23:56,010 INFO    MainThread:21832 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-23 18:23:56,011 INFO    MainThread:21832 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-07-23 18:23:56,011 INFO    MainThread:21832 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-07-23 18:23:56,011 INFO    MainThread:21832 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-07-23 18:23:56,013 INFO    MainThread:21832 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-23 18:23:56,013 INFO    MainThread:21832 [wandb_init.py:_log_setup():529] Logging user logs to c:\Users\PC\Documents\MLCodes\wandb\run-20240723_182355-lftk7w9p\logs\debug.log
2024-07-23 18:23:56,016 INFO    MainThread:21832 [wandb_init.py:_log_setup():530] Logging internal logs to c:\Users\PC\Documents\MLCodes\wandb\run-20240723_182355-lftk7w9p\logs\debug-internal.log
2024-07-23 18:23:56,018 INFO    MainThread:21832 [wandb_init.py:init():569] calling init triggers
2024-07-23 18:23:56,018 INFO    MainThread:21832 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {}
2024-07-23 18:23:56,019 INFO    MainThread:21832 [wandb_init.py:init():594] re-initializing run, found existing run on stack: hkzqy0br
2024-07-23 18:23:56,031 INFO    MainThread:21832 [wandb_run.py:_finish():2109] finishing run cheatcode046-null/ url_classification/hkzqy0br
2024-07-23 18:23:56,033 ERROR   MainThread:21832 [jupyter.py:save_history():436] Run pip install nbformat to save notebook history
2024-07-23 18:23:56,036 INFO    MainThread:21832 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2024-07-23 18:23:56,037 INFO    MainThread:21832 [wandb_init.py:_jupyter_teardown():457] cleaning up jupyter logic
2024-07-23 18:23:56,037 INFO    MainThread:21832 [wandb_run.py:_atexit_cleanup():2349] got exitcode: 0
2024-07-23 18:23:56,037 INFO    MainThread:21832 [wandb_run.py:_restore():2332] restore
2024-07-23 18:23:56,039 INFO    MainThread:21832 [wandb_run.py:_restore():2338] restore done
2024-07-23 18:33:51,527 INFO    MainThread:21832 [wandb_init.py:init():619] starting backend
2024-07-23 18:33:51,530 INFO    MainThread:21832 [wandb_init.py:init():623] setting up manager
2024-07-23 18:33:51,547 INFO    MainThread:21832 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-07-23 18:33:51,555 INFO    MainThread:21832 [wandb_init.py:init():631] backend started and connected
2024-07-23 18:33:51,600 INFO    MainThread:21832 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-07-23 18:33:51,603 INFO    MainThread:21832 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-07-23 18:33:51,603 INFO    MainThread:21832 [wandb_init.py:init():720] updated telemetry
2024-07-23 18:33:51,786 INFO    MainThread:21832 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
